### PR TITLE
Create a handler for outputting schedule in WCIF format.

### PR DESCRIPTION
**Pull request by timreyn**
Not ready to merge yet.

Sample: https://schedule-wcif-dot-staging-cubingusa-org.appspot.com/scheduling/FraminghamFrozenFingers2018/wcif?pretty=1

### CODE REVIEW

**Comment by timreyn** [comment]
Fixes #68 .

**Comment by timreyn** [comment]
Also fixes #45.  This is stable enough that I'm going to merge.

**Comment by jfly** [comment]
Awesome!! Super excited to see this coming together :)

Did @viroulep take a look at this?

**Comment by viroulep** [comment]
I just took a glance at it, as I don't have much time to look at it in details.

I'd really be interested in seeing how an exported WCIF with schedule for a multi-stage competition looks like!

Also glad the WCIF fits CubingUSA's needs :)

**Comment by jfly** [comment]
Good question! @timreyn, is it possible for us to see the WCIF for the upcoming US Nationals?

**Comment by timreyn** [comment]
I posted this on slack: https://cubingusa.org/scheduling/CubingUSANationals2018/wcif?pretty=1

As I said there, it's missing groups currently; that's next on my todo list.

**Pull request merged**
