### PR TITLE
Add partner/sponsor info and filming notice

### PR DESCRIPTION
**Pull request by ToastyKen**

### CODE REVIEW

**Comment by jpbulman** [comment]
Staging [link](https://kenspartnerchanges-dot-staging-cubingusa-org.appspot.com/nationals/2019)

**Comment by jpbulman** [comment]
On the first page under the nats tab, is the sponsors and prizes card supposed to be further down like it is? That's fine if so, just wanted to make sure that was the intention of the design. Besides that, LGTM!

**Comment by ToastyKen** [comment]
It's kinda ugly. I think ideally we'd merge two of the other boxes. Not
sure how best to do that.  Thoughts?

**Comment by ToastyKen** [comment]
Preview: https://kenlutest-dot-staging-cubingusa-org.appspot.com/nationals/2019

**Comment by ToastyKen** [comment]
Hey I'm going to just submit this.

**Pull request merged**
