### PR TITLE
Add info about unofficial events.

### PR DESCRIPTION
**Pull request by timreyn**

### CODE REVIEW

**Comment by KitClement** [comment]
A couple of changes to make to this page:

* Change seminar end time from 9:30 to 9:15
* Add new item on Friday after seminars:

Title: Layer by Layer Live Recording
Time: 9:15-10:15
Description: Andrew Nathenson and Kit Clement's new podcast that is (ostensibly) about cubing will be recording their fourth episode live.

**Comment by nathandwyer** [comment]
Here is the final schedule for seminars: 
8:20-8:35 - “The Growing Role of Technology in Cubing” - Chris Tran
8:40-9:00 - “MultiBLD: You Can Do It Too!” - Mark Boyanowski and Graham Siggins
9:15-10:15 - “Layer By Layer: A Live Podcast with Kit Clement and Andrew Nathansen”

I think it is good to include the podcast recording with the seminars, instead of adding another item. I don't have descriptions for the other seminars (and the titles are pretty self-explanatory), so I merged Kit's description and title for the podcast, for consistency.

**Comment by nathandwyer** [comment]
REVISED final schedule for seminars (actually final this time): 
8:15-8:30 - "The Growing Role of Technology in Cubing" - Chris Tran
8:30-8:45 - "How Cubing Got Us Into College" - Daniel Goodman and Aryan Kejriwal
8:45 -9:00 - "MultiBLD: You Can Do It Too!" - Mark Boyanowski and Graham Siggins
9:15-10:15 - "Layer By Layer: A Live Podcast with Kit Clement and Andrew Nathansen"

**Comment by timreyn** [comment]
Thanks.  Nathan, if there are any more changes needed please file an issue.

**Pull request merged**
