### PR TITLE
Personnel update

### PR DESCRIPTION
**Pull request by ToastyKen**
Updated personnel:
Added Walker as director, with photo
Updated personnel names
Added Last Updated line.

Please verify against the canonical Personnel file (CubingUSA account access only):
https://docs.google.com/spreadsheets/d/1grZdfWCTWQuSmeVEkmndUsdC7YkFJLF3vFOXBoomEZA/edit#gid=2038013259

### CODE REVIEW

**Comment by ToastyKen** [comment]
James and JP, could one of you please review this? Thanks!

**Comment by ToastyKen** [comment]
Would be great if you could help test this branch out in staging, too, since I seem to be having trouble with that. Ask Tim for help. :)

**Comment by FatBoyXPC** [comment]
Edit: D'oh! I thought this was an email!

Hey Ken,

I can take a look at this later tonight!

James

**Comment by jpbulman** [comment]
Hi Kenneth/James,

I checked this out locally and it looks good to me! As far as staging goes, I would need permission for the link in this [doc](https://github.com/cubingusa/org/blob/3ed14c835f500f71d7a64051adcf55afd0b8aeed/doc/staging.md) from @timreyn.

-JP

**Comment by timreyn** [comment]
@jpbulman I granted permission to staging -- I think.  We haven't actually successfully gotten someone else to deploy to staging.

@ToastyKen I found one more permission that looked possibly useful ("App Engine Deployer") and gave it to you as well.

**Comment by jpbulman** [comment]
Thanks @timreyn ! It worked great, the personnel update can be viewed in staging [here](https://jpbulmanpersonnel-dot-staging-cubingusa-org.appspot.com./about/who#walker). Everything looks good to me, does anyone see any problems?

**Comment by ToastyKen** [comment]
@FatBoyXPC Can you double-check all the names against the spreadsheet above and/or our votes?

**Review by FatBoyXPC — APPROVED** [review]
LGTM!

**Pull request merged**
